In [1]:
#Basic numpy array zeros()
import numpy as np

In [2]:
zerosArray = np.zeros(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
zerosArray = zerosArray.astype(int)
print(zerosArray)

[0 0 0 0 0 0 0 0 0 0]


In [1]:
#basic numpy array ones()
import numpy as np

In [2]:
onesArray = np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
onesArray = onesArray.astype(int)
print(onesArray)

[1 1 1 1 1 1 1 1 1 1]


In [4]:
#basic numpy array full()
import numpy as np

In [7]:
prefilledarray = np.full(10,100)

In [8]:
print(prefilledarray)

[100 100 100 100 100 100 100 100 100 100]


In [9]:
#Adding a scalar
import  numpy as np

In [11]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [13]:
print(matrix+10)

[[11 12 13]
 [14 15 16]]


In [17]:
#substracting a scalar
matrix = np.array([[2,2,2],[4,5,6]])
print(matrix)

[[2 2 2]
 [4 5 6]]


In [20]:
print(matrix-1)

[[1 1 1]
 [3 4 5]]


In [21]:
#multipying a scalar
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [22]:
print(matrix*10)

[[10 20 30]
 [40 50 60]]


In [24]:
#divining a scalar
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix/2)
print(matrix//2)

[[1 2 3]
 [4 5 6]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0 1 1]
 [2 2 3]]


In [25]:
#rise to power
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix**2)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [12]:
#transposing a numpy array
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [1]:
#Elementry wise addition 
import numpy as np
matrix1 = np.array([[1,2,3],[4,5,6]])
print(matrix1)

matrix2 = np.array([[-1,-2,-3],[-4,-5,-6]])
print(matrix2)

print(matrix1 + matrix2)

[[1 2 3]
 [4 5 6]]
[[-1 -2 -3]
 [-4 -5 -6]]
[[0 0 0]
 [0 0 0]]


In [2]:
pythonlist1 = [[1,2,3],[4,5,6]]
pythonlist2 = [[-1,-2,-3],[-4,-5,-6]]
print(pythonlist1 + pythonlist2)

[[1, 2, 3], [4, 5, 6], [-1, -2, -3], [-4, -5, -6]]


In [5]:
#elementry wise substraction
import numpy as np
matrix1 = np.array([[1,2,3],[4,5,6]])
print(matrix1)

matrix2 = np.array([[1,2,3],[0,9,8]])
print(matrix2)

print(matrix1 - matrix2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [0 9 8]]
[[ 0  0  0]
 [ 4 -4 -2]]


In [6]:
#elementry wise multiplication
import numpy as np
matrix1 = np.array([[1,2,3],[4,5,6]])
print(matrix1)

matrix2 = np.array([[1,2,3],[0,9,8]])
print(matrix2)

print(matrix1 * matrix2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [0 9 8]]
[[ 1  4  9]
 [ 0 45 48]]


In [1]:
#elementry wise divide
import numpy as np
matrix1 = np.array([[10,20,30],[40,50,60]])
print(matrix1)

matrix2 = np.array([[1,1,1],[1,1,1]])
print(matrix2)

print(matrix1 / matrix2)

[[10 20 30]
 [40 50 60]]
[[1 1 1]
 [1 1 1]]
[[10. 20. 30.]
 [40. 50. 60.]]


In [3]:
#matrix statics operations
import numpy as np

matrix1 = np.array([[1,2,3],[4,5,6]])
print(matrix1)

np.min(matrix1)

np.max(matrix1)

np.sum(matrix1)

np.mean(matrix1)

np.std(matrix1)

np.median(matrix1)

[[1 2 3]
 [4 5 6]]


3.5