In [1]:
import numpy as np

In [2]:
#one dimenisonal array
oneDarray = np.array([1,2,3,4,5])
print(oneDarray)

[1 2 3 4 5]


In [3]:
print(oneDarray.ndim)

1


In [4]:
#two dimensional array
twoDarray = np.array([[1,2,3],[4,5,6]])
print(twoDarray)

[[1 2 3]
 [4 5 6]]


In [5]:
print(twoDarray.ndim)

2


In [6]:
#three dimensional array
threeDarray = np.array([[[1,2,3],[-1,-2,-3],[4,5,6],[-4,-5,-6]]])
print(threeDarray)

[[[ 1  2  3]
  [-1 -2 -3]
  [ 4  5  6]
  [-4 -5 -6]]]


In [7]:
print(threeDarray.ndim)

3


In [4]:
#Iterating Over NumPy Arrays

import numpy as np
twoEarray = np.array(([1,2,3],[4,5,6]))
for i in twoEarray:
    print(i)


[1 2 3]
[4 5 6]


In [5]:
for i in twoEarray:
    for j in i:
        print(j)


1
2
3
4
5
6


In [2]:
import numpy as np
threeDarray = np.array([[[1,2,3],[-1,-2,-3]],[[4,5,6],[-4,-5,-6]]])
for i in threeDarray:
    print(i)

[[ 1  2  3]
 [-1 -2 -3]]
[[ 4  5  6]
 [-4 -5 -6]]


In [3]:
for i in threeDarray:
    for j in i:
        print(j)

[1 2 3]
[-1 -2 -3]
[4 5 6]
[-4 -5 -6]


In [4]:
for i in threeDarray:
    for j in i:
        for k in j:
            print(k)

1
2
3
-1
-2
-3
4
5
6
-4
-5
-6
